# Analisando dados da pesquisa de Mercado!
---
Passamos para final!!!!
<p style ='font-size: 25px; font-family: consolas; color: yellow'>
        Agora vamos focar em entender a tabela tb_cognatis e entender onde podemos evoluir!
</p>

In [2]:
#importando bibliotecas
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#carregando dados cognatis
pesquisa = pd.read_csv('tb_solds_cognatis.csv', sep=';')
pesquisa.head()

,SETOR_ATIV,UF,MUNICIPIO,CEP,TRABALHADORES,S_RENDA_MEDIA,S_FLUXO_PEDESTRE,S_FLUXO_VEICULOS,S_POP_TOTAL,S_DOM_PART_PERM,...,S_DE_50_99_FUNC,S_DE_100_249_FUNC,S_DE_250_499_FUNC,S_DE_500_999_FUNC,S_MAIS1000_FUNC,S_SUPERMERCADO,S_TT_PADARIA,S_ATACADO,S_HIPERMERCADO,S_MINIMERCADO
0,NaN,NaN,NaN,NaN,18776.596364,1852.325903,3.158788,4.933333,61660.275152,22297.529697,...,22.883636,12.442424,4.026667,2.001212,1.670303,8.768485,57.606061,23.126061,2.865455,85.970909
1,NaN,AC,Rio Branco,69900001.0,13125.000000,3502.669922,4.000000,6.000000,53376.000000,17146.000000,...,15.000000,15.000000,3.000000,4.000000,2.000000,3.000000,22.000000,3.000000,9.000000,184.000000
2,NaN,AC,Rio Branco,69900001.0,18364.000000,2477.159912,4.000000,6.000000,73460.000000,24698.000000,...,19.000000,19.000000,6.000000,2.000000,2.000000,14.000000,29.000000,27.000000,9.000000,111.000000
3,NaN,AC,Sena Madureira,NaN,960.000000,1225.869995,0.000000,0.000000,26675.500000,7823.500000,...,1.000000,0.000000,0.000000,0.500000,0.000000,3.000000,7.500000,5.000000,1.000000,84.000000
4,NaN,AC,Senador Guiomard,NaN,1102.000000,1272.079956,0.000000,1.000000,11183.000000,3732.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,10.000000,0.000000,0.000000,42.000000

In [4]:
#Analisando tamanho
pesquisa.shape

(82391, 50)

In [5]:
#Analisando colunas
pesquisa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82391 entries, 0 to 82390
Data columns (total 50 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   SETOR_ATIV                 77558 non-null  object
 1   UF                         82390 non-null  object
 2   MUNICIPIO                  82390 non-null  object
 3   CEP                        80352 non-null  float64
 4   TRABALHADORES              82391 non-null  float64
 5   S_RENDA_MEDIA              82391 non-null  float64
 6   S_FLUXO_PEDESTRE           82391 non-null  float64
 7   S_FLUXO_VEICULOS           82391 non-null  float64
 8   S_POP_TOTAL                82391 non-null  float64
 9   S_DOM_PART_PERM            82391 non-null  float64
 10  S_PCT_CRIANCAS             82391 non-null  float64
 11  S_PCT_ADOLESCENTE          82391 non-null  float64
 12  S_PCT_JOVENS               82391 non-null  float64
 13  S_PCT_ADULTOS              82391 non-null  float64
 14  S_PCT_SENIOR               82391 non-null  float64
 15  S_PCT_IDOSOS               82391 non-null  float64
 16  S_RENDA_MEDIA_FAMILIAR     82391 non-null  float64
 17  S_DENSIDADE_POPULACAO_KM2  82391 non-null  float64
 18  S_PCT_CLASSE_A             82391 non-null  float64
 19  S_PCT_CLASSE_B             82391 non-null  float64
 20  S_PCT_CLASSE_C             82391 non-null  float64
 21  S_PCT_CLASSE_D             82391 non-null  float64
 22  S_PCT_CLASSE_E             82391 non-null  float64
 23  S_TX_CRESC_POP             82391 non-null  float64
 24  S_TX_CRESC_DOM             82391 non-null  float64
 25  S_TX_CRESC_RENDA_MEDIA     82391 non-null  float64
 26  S_RENDA_PER_CAPITA         82391 non-null  float64
 27  S_COMERCIALIZACAO          82391 non-null  float64
 28  S_QTD_EMPRESAS             82391 non-null  float64
 29  S_PCT_CNAE_AGRICOLA        82391 non-null  float64
 30  S_PCT_CNAE_COMERCIO        82391 non-null  float64
 31  S_PCT_CNAE_CONSTR_CIVIL    82391 non-null  float64
 32  S_PCT_CNAE_INDUSTRIA       82391 non-null  float64
 33  S_PCT_CNAE_SERVICOS        82391 non-null  float64
 34  S_PCT_CNAE_OUTROS          82391 non-null  float64
 35  S_SEM_FUNC                 82391 non-null  float64
 36  S_DE_1_4_FUNC              82391 non-null  float64
 37  S_DE_5_9_FUNC              82391 non-null  float64
 38  S_DE_10_19_FUNC            82391 non-null  float64
 39  S_DE_20_49_FUNC            82391 non-null  float64
 40  S_DE_50_99_FUNC            82391 non-null  float64
 41  S_DE_100_249_FUNC          82391 non-null  float64
 42  S_DE_250_499_FUNC          82391 non-null  float64
 43  S_DE_500_999_FUNC          82391 non-null  float64
 44  S_MAIS1000_FUNC            82391 non-null  float64
 45  S_SUPERMERCADO             82391 non-null  float64
 46  S_TT_PADARIA               82391 non-null  float64
 47  S_ATACADO                  82391 non-null  float64
 48  S_HIPERMERCADO             82391 non-null  float64
 49  S_MINIMERCADO              82391 non-null  float64
dtypes: float64(47), object(3)
memory usage: 31.4+ MB

In [6]:
#Pegando nome de colunas
pesquisa.columns

Index(['SETOR_ATIV', 'UF', 'MUNICIPIO', 'CEP', 'TRABALHADORES',
       'S_RENDA_MEDIA', 'S_FLUXO_PEDESTRE', 'S_FLUXO_VEICULOS', 'S_POP_TOTAL',
       'S_DOM_PART_PERM', 'S_PCT_CRIANCAS', 'S_PCT_ADOLESCENTE',
       'S_PCT_JOVENS', 'S_PCT_ADULTOS', 'S_PCT_SENIOR', 'S_PCT_IDOSOS',
       'S_RENDA_MEDIA_FAMILIAR', 'S_DENSIDADE_POPULACAO_KM2', 'S_PCT_CLASSE_A',
       'S_PCT_CLASSE_B', 'S_PCT_CLASSE_C', 'S_PCT_CLASSE_D', 'S_PCT_CLASSE_E',
       'S_TX_CRESC_POP', 'S_TX_CRESC_DOM', 'S_TX_CRESC_RENDA_MEDIA',
       'S_RENDA_PER_CAPITA', 'S_COMERCIALIZACAO', 'S_QTD_EMPRESAS',
       'S_PCT_CNAE_AGRICOLA', 'S_PCT_CNAE_COMERCIO', 'S_PCT_CNAE_CONSTR_CIVIL',
       'S_PCT_CNAE_INDUSTRIA', 'S_PCT_CNAE_SERVICOS', 'S_PCT_CNAE_OUTROS',
       'S_SEM_FUNC', 'S_DE_1_4_FUNC', 'S_DE_5_9_FUNC', 'S_DE_10_19_FUNC',
       'S_DE_20_49_FUNC', 'S_DE_50_99_FUNC', 'S_DE_100_249_FUNC',
       'S_DE_250_499_FUNC', 'S_DE_500_999_FUNC', 'S_MAIS1000_FUNC',
       'S_SUPERMERCADO', 'S_TT_PADARIA', 'S_ATACADO', 'S_HIPERMERCADO',
       'S_MINIMERCADO'],
      dtype='object')

In [7]:
#Analisando cidades
cidades = pesquisa.groupby('MUNICIPIO')['MUNICIPIO'].count()
cidades.sort_values(ascending=False, inplace= True)
cidades.head(10)

MUNICIPIO
SAO PAULO         3999
RIO DE JANEIRO    2165
FORTALEZA         2099
BELO HORIZONTE    1727
BRASILIA          1629
CURITIBA          1524
SALVADOR          1274
MACEIO             998
PORTO ALEGRE       961
TERESINA           866
Name: MUNICIPIO, dtype: int64

In [8]:
#analisando duplicados
pesquisa.loc[(pesquisa.duplicated()) & (pesquisa['MUNICIPIO'] == 'SAO PAULO'), ['S_PCT_CLASSE_A','S_PCT_CLASSE_B', 'S_PCT_CLASSE_C', 'S_PCT_CLASSE_D', 'S_PCT_CLASSE_E']].head(10)

,S_PCT_CLASSE_A,S_PCT_CLASSE_B,S_PCT_CLASSE_C,S_PCT_CLASSE_D,S_PCT_CLASSE_E
61925,0.29,20.280001,63.680000,15.11,0.64
61969,0.06,16.129999,64.680000,18.40,0.74
62324,0.43,21.820000,61.730000,15.54,0.47
63023,1.78,32.310001,55.860001,8.84,1.21
63044,0.06,16.129999,64.650002,18.42,0.74
63266,1.53,38.060001,48.759998,11.36,0.30
63547,0.28,36.279999,55.279999,7.82,0.35

In [9]:
#vamos fazer um scrapping
import requests 
from bs4 import BeautifulSoup as bs

In [10]:
#vamos fazer o pedido do site
site = requests.get('https://ajuda.komercialize.com.br/Post/66181/faixas-de-cep-por-bairros-de-sao-paulo')
site.status_code

200

In [11]:
#Agora vamos pegar seu conteudo
conteudo = site.content

#agora vamos passar para o beautifulsoup
soup = bs(conteudo, 'lxml')
tabela = soup('table')[0]
tabela

<table class="table table-striped">
<tbody>
<tr>
<td>Zona</td>
<td>Bairros</td>
<td>Inicio</td>
<td>Fim</td>
</tr>
<tr>
<td>Centro</td>
<td>Sé<br/> Santa Efigênia<br/> República<br/> Centro</td>
<td>01000-000</td>
<td>01099-999</td>
</tr>
<tr>
<td>Centro</td>
<td>Barra Funda<br/> Bom Retiro<br/> Luz<br/> Ponte Pequena</td>
<td>01100-000</td>
<td>01199-999</td>
</tr>
<tr>
<td>Centro</td>
<td>Santa Cecília/ Pacaembú<br/> Sumaré<br/> Higienópolis<br/> Consolação</td>
<td>01200-000</td>
<td>01299-999</td>
</tr>
<tr>
<td>Centro</td>
<td>Consolação<br/> Bela Vista</td>
<td>01300-000</td>
<td>01399-999</td>
</tr>
<tr>
<td>Centro</td>
<td>Cerqueira César<br/> Jardim Paulista<br/> Jardim América<br/> Jardim Europa</td>
<td>01400-000</td>
<td>01499-999</td>
</tr>
<tr>
<td>Centro</td>
<td>Liberdade<br/> Cambuci<br/> Aclimação<br/> Vila Monumento<br/> Jardimda Glória</td>
<td>01500-000</td>
<td>01599-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Santana<br/> Carandiru<br/> Vila Guilherme<br/> Jardim São Paulo</td>
<td>02000-000</td>
<td>02099-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Vila Maria<br/> Parque Novo Mundo<br/> Jardim Japão</td>
<td>02100-000</td>
<td>02199-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Tucuruvi<br/> Jaçanã<br/> Parque Edu Chaves<br/> Vila Medeiros<br/> Vila Edi</td>
<td>02200-000</td>
<td>02299-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Jardim Tremembé<br/> Barro Branco<br/> Água Fria</td>
<td>02300-000</td>
<td>02399-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Mandaqui<br/> Imirim<br/> Lausane Paulista<br/> Santa Teresinha</td>
<td>02400-000</td>
<td>02499-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Casa Verde<br/> Parque Peruche</td>
<td>02500-000</td>
<td>02599-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Vila Nova Cachoeirinha<br/> Jardim Peri Peri</td>
<td>02600-000</td>
<td>02699-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Limão<br/> Nossa Senhora do Ó<br/> Itaberaba</td>
<td>02700-000</td>
<td>02799-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Brasilândia<br/> Morro Grande</td>
<td>02800-000</td>
<td>02899-999</td>
</tr>
<tr>
<td>Zona Norte</td>
<td>Freguesia do Ó<br/> Pirituba<br/> Piqueri</td>
<td>02900-000</td>
<td>02999-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Belenzinho<br/> Brás<br/> Belém<br/> Pari<br/> Canindé<br/> Catumbi<br/> ParqueS.Jorge</td>
<td>03000-000</td>
<td>03099-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Moóca<br/> Alto da Moóca<br/> Vila Prudente<br/> A. Rosa<br/> Quarta Parada<br/> Parque Moóca<br/> Vila Zelina</td>
<td>03100-000</td>
<td>03199-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>VilaEma<br/> Parque São Lucas<br/> Vila Alpina<br/> Sapopemba</td>
<td>03200-000</td>
<td>03299-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Tatuapé<br/> Vila Formosa<br/> Jardim Colorado<br/> Vila Gomes Cardim<br/> JardimAnália Franco</td>
<td>03300-000</td>
<td>03399-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Vila Carrão<br/> Carrãozinho</td>
<td>03400-000</td>
<td>03499-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Vila Matilde<br/> Cidade Patriarca<br/> Artur Alvim</td>
<td>03500-000</td>
<td>03599-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Penha<br/> Vila Esperança<br/> Vila Ré<br/> Cidade A. E. Carvalho</td>
<td>03600-000</td>
<td>03699-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Cangaiba<br/> Engenho Goulart<br/> Ponte Rasa</td>
<td>03700-000</td>
<td>03799-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>Ermelino Matarazzo<br/> Vila Paranaguá</td>
<td>03800-000</td>
<td>03899-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>São Mateus<br/> Iguaçu</td>
<td>03900-000</td>
<td>03999-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>SÃO MIGUEL PAULISTA</td>
<td>08000-000</td>
<td>08099-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>ITAIM PAULISTA</td>
<td>08100-000</td>
<td>08199-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>ITAQUERA</td>
<td>08200-000</td>
<td>08299-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>SÃO MATEUS</td>
<td>08300-000</td>
<td>08399-999</td>
</tr>
<tr>
<td>Zona Leste</td>
<td>GUAIANAZES</td>
<td>08400-000</td>
<td>08499-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Vila Mariana<br/> Vila Clementino<br/> Paraíso<br/> Indianópolis<br/> Moema<br/> Planalto Paulista<br/> Mirandópolis</td>
<td>04000-000</td>
<td>04099-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Jardim Glória<br/> Saúde<br/> Água Funda<br/> Vila Mercês<br/> Vila Liviero</td>
<td>04100-000</td>
<td>04199-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Ipiranga<br/> Vila Carioca<br/> Sacomã<br/> Moinho Velho<br/> São João Clímaco</td>
<td>04200-000</td>
<td>04299-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Jabaquara<br/> Jardim Aeroporto<br/> Vila Sta Catarina<br/> Vila Guarani<br/> Vila Mascote</td>
<td>04300-000</td>
<td>04399-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Cidade Ademar<br/> Pedreira<br/> Jardim Miriam<br/> Americanópolis</td>
<td>04400-000</td>
<td>04499-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Brooklin Novo<br/> Itaim Bibi<br/> Vila Olímpia<br/> Moema<br/> Vila Nova Conceição</td>
<td>04500-000</td>
<td>04599-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Brooklin Paulista<br/> Campo Belo<br/> Aeroporto<br/> Cidade Ademar<br/> Campo Grande<br/> Jurubatuba<br/> Chácara Flora<br/> Chácara Monte Alegre</td>
<td>04600-000</td>
<td>04699-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Santo Amaro<br/> Chácara Santo Antônio<br/> Granja Julieta<br/> Socorro<br/> Veleiros<br/> Interlagos<br/> Alto da Boa Vista</td>
<td>04700-000</td>
<td>04799-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Cidade Dutra<br/> Rio Bonito<br/> Parque Grajaú<br/> Parelheiros</td>
<td>04800-000</td>
<td>04899-999</td>
</tr>
<tr>
<td>Zona Sul</td>
<td>Guarapiranga<br/> Capela do Socorro</td>
<td>04900-000</td>
<td>04999-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Lapa<br/> Perdizes<br/> Água Branca<br/> Alto da Lapa<br/> Vila Anastácia<br/> Pompéia<br/> Vila Romana</td>
<td>05000-000</td>
<td>05099-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Vila Jaguara<br/> Pirituba<br/> Parque São Domingos</td>
<td>05100-000</td>
<td>05199-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Jaraguá<br/> Perus</td>
<td>05200-000</td>
<td>05299-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Vila Leopoldina<br/> Ceasa<br/> Jaguaré<br/> Rio Pequeno<br/> Vila Hamburguesa<br/> Vila Remédios</td>
<td>05300-000</td>
<td>05399-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Pinheiros<br/> Vila Madalena<br/> Alto de Pinheiros</td>
<td>05400-000</td>
<td>05499-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Butantã<br/> Caxingui<br/> Cidade Universitária (USP)<br/> Jardim Peri-Peri<br/> Jardim Bonfiglioli</td>
<td>05500-000</td>
<td>05599-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Cidade Jardim<br/> Morumbi<br/> Vila Sônia<br/> Jardim Guedala<br/> Jardim Leonor<br/> Real Parque</td>
<td>05600-000</td>
<td>05699-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Campo Limpo<br/> Pirajuçara</td>
<td>05700-000</td>
<td>05799-999</td>
</tr>
<tr>
<td>Zona Oeste</td>
<td>Capão Redondo<br/> Vila Das Belezas</td>
<td>05800-000</td>
<td>05899-999</td>
</tr>
</tbody>
</table>

In [12]:
#lendo para um df
tabela_ceps = pd.read_html(tabela.prettify(), header=0, flavor='bs4')[0]
tabela_ceps.to_csv('zonas_cep.csv')

In [13]:
#verificando tabela
tabela_ceps

,Zona,Bairros,Inicio,Fim
0,Centro,Sé Santa Efigênia República Centro,01000-000,01099-999
1,Centro,Barra Funda Bom Retiro Luz Ponte Pequena,01100-000,01199-999
2,Centro,Santa Cecília/ Pacaembú Sumaré Higienópolis ...,01200-000,01299-999
3,Centro,Consolação Bela Vista,01300-000,01399-999
4,Centro,Cerqueira César Jardim Paulista Jardim Améri...,01400-000,01499-999
5,Centro,Liberdade Cambuci Aclimação Vila Monumento ...,01500-000,01599-999
6,Zona Norte,Santana Carandiru Vila Guilherme Jardim São...,02000-000,02099-999
7,Zona Norte,Vila Maria Parque Novo Mundo Jardim Japão,02100-000,02199-999
8,Zona Norte,Tucuruvi Jaçanã Parque Edu Chaves Vila Mede...,02200-000,02299-999
9,Zona Norte,Jardim Tremembé Barro Branco Água Fria,02300-000,02399-999
10,Zona Norte,Mandaqui Imirim Lausane Paulista Santa Tere...,02400-000,02499-999
11,Zona Norte,Casa Verde Parque Peruche,02500-000,02599-999
12,Zona Norte,Vila Nova Cachoeirinha Jardim Peri Peri,02600-000,02699-999
13,Zona Norte,Limão Nossa Senhora do Ó Itaberaba,02700-000,02799-999
14,Zona Norte,Brasilândia Morro Grande,02800-000,02899-999
15,Zona Norte,Freguesia do Ó Pirituba Piqueri,02900-000,02999-999
16,Zona Leste,Belenzinho Brás Belém Pari Canindé Catumb...,03000-000,03099-999
17,Zona Leste,Moóca Alto da Moóca Vila Prudente A. Rosa ...,03100-000,03199-999
18,Zona Leste,VilaEma Parque São Lucas Vila Alpina Sapopemba,03200-000,03299-999
19,Zona Leste,Tatuapé Vila Formosa Jardim Colorado Vila G...,03300-000,03399-999
20,Zona Leste,Vila Carrão Carrãozinho,03400-000,03499-999
21,Zona Leste,Vila Matilde Cidade Patriarca Artur Alvim,03500-000,03599-999
22,Zona Leste,Penha Vila Esperança Vila Ré Cidade A. E. C...,03600-000,03699-999
23,Zona Leste,Cangaiba Engenho Goulart Ponte Rasa,03700-000,03799-999
24,Zona Leste,Ermelino Matarazzo Vila Paranaguá,03800-000,03899-999
25,Zona Leste,São Mateus Iguaçu,03900-000,03999-999
26,Zona Leste,SÃO MIGUEL PAULISTA,08000-000,08099-999
27,Zona Leste,ITAIM PAULISTA,08100-000,08199-999
28,Zona Leste,ITAQUERA,08200-000,08299-999
29,Zona Leste,SÃO MATEUS,08300-000,08399-999
30,Zona Leste,GUAIANAZES,08400-000,08499-999
31,Zona Sul,Vila Mariana Vila Clementino Paraíso Indian...,04000-000,04099-999
32,Zona Sul,Jardim Glória Saúde Água Funda Vila Mercês ...,04100-000,04199-999
33,Zona Sul,Ipiranga Vila Carioca Sacomã Moinho Velho ...,04200-000,04299-999
34,Zona Sul,Jabaquara Jardim Aeroporto Vila Sta Catarina...,04300-000,04399-999
35,Zona Sul,Cidade Ademar Pedreira Jardim Miriam Americ...,04400-000,04499-999
36,Zona Sul,Brooklin Novo Itaim Bibi Vila Olímpia Moema...,04500-000,04599-999
37,Zona Sul,Brooklin Paulista Campo Belo Aeroporto Cida...,04600-000,04699-999
38,Zona Sul,Santo Amaro Chácara Santo Antônio Granja Jul...,04700-000,04799-999
39,Zona Sul,Cidade Dutra Rio Bonito Parque Grajaú Parel...,04800-000,04899-999
40,Zona Sul,Guarapiranga Capela do Socorro,04900-000,04999-999
41,Zona Oeste,Lapa Perdizes Água Branca Alto da Lapa Vil...,05000-000,05099-999
42,Zona Oeste,Vila Jaguara Pirituba Parque São Domingos,05100-000,05199-999
43,Zona Oeste,Jaraguá Perus,05200-000,05299-999
44,Zona Oeste,Vila Leopoldina Ceasa Jaguaré Rio Pequeno ...,05300-000,05399-999
45,Zona Oeste,Pinheiros Vila Madalena Alto de Pinheiros,05400-000,05499-999
46,Zona Oeste,Butantã Caxingui Cidade Universitária (USP) ...,05500-000,05599-999
47,Zona Oeste,Cidade Jardim Morumbi Vila Sônia Jardim Gue...,05600-000,05699-999
48,Zona Oeste,Campo Limpo Pirajuçara,05700-000,05799-999
49,Zona Oeste,Capão Redondo Vila Das Belezas,05800-000,05899-999

In [14]:
#Agora que temos um mapeamento de regiões, vamos fazer uma classificação do que tem no nosso dataset
pesquisa['CEP'].fillna(0, inplace=True)
pesquisa['cep_correto'] = pesquisa['CEP'].apply(lambda x: int(x))

In [15]:
#Pegando CEP de SP
ceps_sp = pesquisa[pesquisa['MUNICIPIO'] == 'SAO PAULO']
ceps_sp.head()

,SETOR_ATIV,UF,MUNICIPIO,CEP,TRABALHADORES,S_RENDA_MEDIA,S_FLUXO_PEDESTRE,S_FLUXO_VEICULOS,S_POP_TOTAL,S_DOM_PART_PERM,...,S_DE_100_249_FUNC,S_DE_250_499_FUNC,S_DE_500_999_FUNC,S_MAIS1000_FUNC,S_SUPERMERCADO,S_TT_PADARIA,S_ATACADO,S_HIPERMERCADO,S_MINIMERCADO,cep_correto
4872,AGROPECUARIA,SP,SAO PAULO,49400000.0,8889.0,1787.380005,4.0,6.0,158260.0,53622.0,...,1.0,1.0,1.0,2.0,12.0,162.0,16.0,2.0,297.0,49400000
4873,AGROPECUARIA,SP,SAO PAULO,55290001.0,17338.0,1712.239990,4.0,6.0,105274.0,36930.0,...,23.0,4.0,4.0,1.0,9.0,103.0,35.0,2.0,86.0,55290001
4874,AGROPECUARIA,SP,SAO PAULO,40000001.0,16464.0,2532.110107,4.0,6.0,144552.0,51111.0,...,11.0,4.0,2.0,2.0,7.0,143.0,38.0,4.0,130.0,40000001
4875,AGROPECUARIA,SP,SAO PAULO,44750000.0,8597.0,1514.410034,4.0,6.0,136200.0,45121.0,...,0.0,0.0,2.0,2.0,14.0,124.0,10.0,3.0,175.0,44750000
60294,COMERCIO,SP,SAO PAULO,0.0,377814.0,4078.379028,5.0,6.0,210052.0,104878.0,...,179.0,74.0,46.5,46.0,47.0,262.0,129.0,10.5,326.5,0

In [16]:
#Criando a ordem do CEP
ceps_sp['CEP_ORD'] = ceps_sp['cep_correto'].apply(lambda x: '0' + str(x)[:2])

<ipython-input-16-5dfaf0cb15c3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ceps_sp['CEP_ORD'] = ceps_sp['cep_correto'].apply(lambda x: '0' + str(x)[:2])

In [17]:
#Criando ordem no nosso dataset do scrapping
tabela_ceps['CEP_ORD'] = tabela_ceps['Inicio'].apply(lambda x: x[:3])
tabela_ceps.head()
ordem_zonas = tabela_ceps[['Zona', 'CEP_ORD']]
ordem_zonas

          Zona CEP_ORD
0       Centro     010
1       Centro     011
2       Centro     012
3       Centro     013
4       Centro     014
5       Centro     015
6   Zona Norte     020
7   Zona Norte     021
8   Zona Norte     022
9   Zona Norte     023
10  Zona Norte     024
11  Zona Norte     025
12  Zona Norte     026
13  Zona Norte     027
14  Zona Norte     028
15  Zona Norte     029
16  Zona Leste     030
17  Zona Leste     031
18  Zona Leste     032
19  Zona Leste     033
20  Zona Leste     034
21  Zona Leste     035
22  Zona Leste     036
23  Zona Leste     037
24  Zona Leste     038
25  Zona Leste     039
26  Zona Leste     080
27  Zona Leste     081
28  Zona Leste     082
29  Zona Leste     083
30  Zona Leste     084
31    Zona Sul     040
32    Zona Sul     041
33    Zona Sul     042
34    Zona Sul     043
35    Zona Sul     044
36    Zona Sul     045
37    Zona Sul     046
38    Zona Sul     047
39    Zona Sul     048
40    Zona Sul     049
41  Zona Oeste     050
42  Zona Oeste     051
43  Zona Oeste     052
44  Zona Oeste     053
45  Zona Oeste     054
46  Zona Oeste     055
47  Zona Oeste     056
48  Zona Oeste     057
49  Zona Oeste     058

In [19]:
ceps_sp_zonas = ceps_sp.merge(ordem_zonas, how='left', on='CEP_ORD')
ceps_sp_zonas.drop((ceps_sp_zonas.loc[ceps_sp_zonas['Zona'].isna()].index), inplace = True)
ceps_sp_zonas.shape

(3598, 53)

In [64]:
ceps_sp_zonas.to_excel('sao_paulo_zonas.xlsx')

In [63]:
ceps_sp_zonas.loc[ceps_sp_zonas['Zona'] == 'Zona Sul'].mean().to

CEP                          4.415010e+07
TRABALHADORES                5.342292e+04
S_RENDA_MEDIA                2.690998e+03
S_FLUXO_PEDESTRE             4.557211e+00
S_FLUXO_VEICULOS             5.983673e+00
S_POP_TOTAL                  1.137242e+05
S_DOM_PART_PERM              4.382523e+04
S_PCT_CRIANCAS               1.020654e+01
S_PCT_ADOLESCENTE            1.116797e+01
S_PCT_JOVENS                 1.393291e+01
S_PCT_ADULTOS                3.361026e+01
S_PCT_SENIOR                 1.908665e+01
S_PCT_IDOSOS                 1.199550e+01
S_RENDA_MEDIA_FAMILIAR       9.610970e+03
S_DENSIDADE_POPULACAO_KM2    1.084414e+04
S_PCT_CLASSE_A               1.162773e+01
S_PCT_CLASSE_B               4.174979e+01
S_PCT_CLASSE_C               3.835460e+01
S_PCT_CLASSE_D               7.849885e+00
S_PCT_CLASSE_E               4.173309e-01
S_TX_CRESC_POP               1.177408e+00
S_TX_CRESC_DOM               2.784140e+00
S_TX_CRESC_RENDA_MEDIA       1.008212e+00
S_RENDA_PER_CAPITA           4.002125e+03
S_COMERCIALIZACAO            2.175626e+01
S_QTD_EMPRESAS               1.818422e+04
S_PCT_CNAE_AGRICOLA          1.436548e-01
S_PCT_CNAE_COMERCIO          2.271702e+01
S_PCT_CNAE_CONSTR_CIVIL      6.409992e+00
S_PCT_CNAE_INDUSTRIA         5.749341e+00
S_PCT_CNAE_SERVICOS          6.451064e+01
S_PCT_CNAE_OUTROS            4.442772e-01
S_SEM_FUNC                   1.216097e+04
S_DE_1_4_FUNC                1.663207e+03
S_DE_5_9_FUNC                6.540550e+02
S_DE_10_19_FUNC              3.572784e+02
S_DE_20_49_FUNC              2.276396e+02
S_DE_50_99_FUNC              6.870830e+01
S_DE_100_249_FUNC            3.835750e+01
S_DE_250_499_FUNC            1.209425e+01
S_DE_500_999_FUNC            6.163275e+00
S_MAIS1000_FUNC              4.828564e+00
S_SUPERMERCADO               1.724315e+01
S_TT_PADARIA                 1.160794e+02
S_ATACADO                    3.974626e+01
S_HIPERMERCADO               4.503570e+00
S_MINIMERCADO                1.168407e+02
cep_correto                  4.415010e+07
CEP_ORD                               inf
dtype: float64

In [20]:
ceps_sp_zonas.columns

Index(['SETOR_ATIV', 'UF', 'MUNICIPIO', 'CEP', 'TRABALHADORES',
       'S_RENDA_MEDIA', 'S_FLUXO_PEDESTRE', 'S_FLUXO_VEICULOS', 'S_POP_TOTAL',
       'S_DOM_PART_PERM', 'S_PCT_CRIANCAS', 'S_PCT_ADOLESCENTE',
       'S_PCT_JOVENS', 'S_PCT_ADULTOS', 'S_PCT_SENIOR', 'S_PCT_IDOSOS',
       'S_RENDA_MEDIA_FAMILIAR', 'S_DENSIDADE_POPULACAO_KM2', 'S_PCT_CLASSE_A',
       'S_PCT_CLASSE_B', 'S_PCT_CLASSE_C', 'S_PCT_CLASSE_D', 'S_PCT_CLASSE_E',
       'S_TX_CRESC_POP', 'S_TX_CRESC_DOM', 'S_TX_CRESC_RENDA_MEDIA',
       'S_RENDA_PER_CAPITA', 'S_COMERCIALIZACAO', 'S_QTD_EMPRESAS',
       'S_PCT_CNAE_AGRICOLA', 'S_PCT_CNAE_COMERCIO', 'S_PCT_CNAE_CONSTR_CIVIL',
       'S_PCT_CNAE_INDUSTRIA', 'S_PCT_CNAE_SERVICOS', 'S_PCT_CNAE_OUTROS',
       'S_SEM_FUNC', 'S_DE_1_4_FUNC', 'S_DE_5_9_FUNC', 'S_DE_10_19_FUNC',
       'S_DE_20_49_FUNC', 'S_DE_50_99_FUNC', 'S_DE_100_249_FUNC',
       'S_DE_250_499_FUNC', 'S_DE_500_999_FUNC', 'S_MAIS1000_FUNC',
       'S_SUPERMERCADO', 'S_TT_PADARIA', 'S_ATACADO', 'S_HIPERMERCADO',
       'S_MINIMERCADO', 'cep_correto', 'CEP_ORD', 'Zona'],
      dtype='object')

In [21]:
colunas_modelo = ceps_sp_zonas[['TRABALHADORES',
       'S_RENDA_MEDIA', 'S_POP_TOTAL',
       'S_DOM_PART_PERM', 'S_PCT_CRIANCAS', 'S_PCT_ADOLESCENTE',
       'S_PCT_JOVENS', 'S_PCT_ADULTOS', 'S_PCT_SENIOR', 'S_PCT_IDOSOS',
       'S_PCT_CLASSE_A','S_PCT_CLASSE_B', 'S_PCT_CLASSE_C', 'S_PCT_CLASSE_D', 'S_PCT_CLASSE_E',
       'S_SUPERMERCADO', 'S_TT_PADARIA', 'S_ATACADO', 'S_HIPERMERCADO',
       'S_MINIMERCADO', 'Zona']]

mapa = {
        'Zona Sul': 0,
        'Centro': 1,
        'Zona Leste': 2,
        'Zona Oeste': 3,
        'Zona Norte': 4, 
}

colunas_modelo['Zona'] = colunas_modelo['Zona'].map(mapa)

<ipython-input-21-7748eada7c2c>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo['Zona'] = colunas_modelo['Zona'].map(mapa)

<h1 style = 'font-family: consolas; color: yellow; font-size: 75px'>
            M01
</h1>

---

In [22]:
#Importando bibliotecas de modelos
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

for coluna in colunas_modelo.columns: #realizando a normalização das colunas
    normalizar = MinMaxScaler()
    if coluna != 'Zona':
        colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
    else:
        continue

#verificando
colunas_modelo.head()

<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))
<ipython-input-22-c1d26aaed431>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  colunas_modelo[coluna] = normalizar.fit_transform(np.array(colunas_modelo[coluna]).reshape(-1, 1))

,TRABALHADORES,S_RENDA_MEDIA,S_POP_TOTAL,S_DOM_PART_PERM,S_PCT_CRIANCAS,S_PCT_ADOLESCENTE,S_PCT_JOVENS,S_PCT_ADULTOS,S_PCT_SENIOR,S_PCT_IDOSOS,...,S_PCT_CLASSE_B,S_PCT_CLASSE_C,S_PCT_CLASSE_D,S_PCT_CLASSE_E,S_SUPERMERCADO,S_TT_PADARIA,S_ATACADO,S_HIPERMERCADO,S_MINIMERCADO,Zona
0,0.019725,0.151899,0.673979,0.448266,0.670463,0.734043,0.727597,0.585324,0.266256,0.156216,...,0.195502,0.923378,0.584376,0.258462,0.176471,0.462428,0.053156,0.117647,0.804333,0
1,0.038485,0.138027,0.443114,0.305732,0.433561,0.465046,0.655036,0.523891,0.566372,0.381738,...,0.732026,0.540093,0.234359,0.175385,0.132353,0.291908,0.116279,0.117647,0.232905,3
2,0.036545,0.289386,0.614252,0.426825,0.441154,0.478723,0.482553,0.594710,0.564833,0.401540,...,0.597270,0.690485,0.266148,0.184615,0.102941,0.407514,0.126246,0.235294,0.352065,0
3,0.019076,0.101505,0.577862,0.375676,0.664389,0.746201,0.689532,0.616041,0.279338,0.140264,...,0.244137,0.896116,0.551573,0.181538,0.205882,0.352601,0.033223,0.176471,0.473934,0
5,0.596774,0.446625,0.888380,0.902313,0.026576,0.091185,0.841792,0.568259,0.743363,0.705721,...,0.719531,0.469530,0.113629,0.110769,0.852941,0.719653,0.425249,0.470588,0.579553,1

In [23]:
#Separando nossos dados
xtrain, xtest, ytrain, ytest = train_test_split(colunas_modelo.iloc[:, :-1], colunas_modelo.iloc[:, -1] , test_size=0.25)

#treinando modelo
floresta = RandomForestClassifier(n_estimators=5)
floresta.fit(xtrain, ytrain)
resultado = floresta.predict(xtest)
df_modelo_prev = pd.DataFrame({'Previsa': resultado, 'Correta':ytest})
df_modelo_prev.head(25)

      Previsa  Correta
2578        3        3
2393        0        3
71          0        0
120         4        4
1128        2        2
136         1        1
3074        3        3
807         3        3
1291        4        4
2218        3        3
348         0        0
2867        2        2
3382        3        3
307         0        0
3198        1        1
1855        2        2
796         2        2
3321        1        1
1953        4        4
1510        3        3
68          4        4
1924        2        2
1943        4        3
2850        0        3
1629        2        2

In [24]:
#verificando acertividade do modelo
from sklearn.metrics import confusion_matrix, accuracy_score

print('Matriz de confusão\n', confusion_matrix(ytest, resultado))
print('\nAcurácia do Modelo\n', accuracy_score(ytest, resultado))

Matriz de confusão
 [[236   3   1  11   2]
 [  2  53   1   3   0]
 [  8   0 254   3   4]
 [ 13   1   1 131   2]
 [  7   0  12   4 148]]

Acurácia do Modelo
 0.9133333333333333

<h1 style = 'color: #58a4b0'>
    Vamos testar com cross validation
</h1>

---

In [25]:
#Usando cross validation
from sklearn.model_selection import cross_val_score
floresta_cross = RandomForestClassifier(n_estimators=5, random_state=42)
score_cv = cross_val_score(floresta_cross, colunas_modelo.iloc[: , :-1], colunas_modelo.iloc[:, -1], cv = 5)
score_cv

array([0.91111111, 0.89166667, 0.90277778, 0.90820584, 0.9054242 ])

In [26]:
#Média da validação cruzada
print('Acurácia: %0.2f (+/- %0.2f)' %(score_cv.mean(), score_cv.std()*2))

Acurácia: 0.90 (+/- 0.01)

<h1 style = 'color: #a9bcd0'> Vamos tentar prever os dados do BRASIL </h1>

---

In [28]:
#pegando os numeros do Brasil
ceps_geral = pesquisa[pesquisa['MUNICIPIO'] != 'SAO PAULO']
teste_geral = ceps_geral[['TRABALHADORES',
       'S_RENDA_MEDIA', 'S_POP_TOTAL',
       'S_DOM_PART_PERM', 'S_PCT_CRIANCAS', 'S_PCT_ADOLESCENTE',
       'S_PCT_JOVENS', 'S_PCT_ADULTOS', 'S_PCT_SENIOR', 'S_PCT_IDOSOS',
       'S_PCT_CLASSE_A','S_PCT_CLASSE_B', 'S_PCT_CLASSE_C', 'S_PCT_CLASSE_D', 'S_PCT_CLASSE_E',
       'S_SUPERMERCADO', 'S_TT_PADARIA', 'S_ATACADO', 'S_HIPERMERCADO',
       'S_MINIMERCADO']]

for i in teste_geral.columns:
    normalizar = MinMaxScaler()
    teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))

teste_geral

<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))
<ipython-input-28-89789d37d75b>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teste_geral[i] = normalizar.fit_transform(np.array(teste_geral[i]).reshape(-1, 1))

,TRABALHADORES,S_RENDA_MEDIA,S_POP_TOTAL,S_DOM_PART_PERM,S_PCT_CRIANCAS,S_PCT_ADOLESCENTE,S_PCT_JOVENS,S_PCT_ADULTOS,S_PCT_SENIOR,S_PCT_IDOSOS,S_PCT_CLASSE_A,S_PCT_CLASSE_B,S_PCT_CLASSE_C,S_PCT_CLASSE_D,S_PCT_CLASSE_E,S_SUPERMERCADO,S_TT_PADARIA,S_ATACADO,S_HIPERMERCADO,S_MINIMERCADO
0,0.046441,0.060365,0.215233,0.209624,0.199246,0.396206,0.236741,0.656518,0.525101,0.384124,0.086368,0.447002,0.585689,0.193301,0.042241,0.099642,0.216158,0.095365,0.062292,0.117447
1,0.032463,0.114147,0.186316,0.161194,0.264292,0.526853,0.273777,0.616807,0.371150,0.236698,0.009396,0.145350,0.571778,0.405200,0.122087,0.034091,0.082552,0.012371,0.195652,0.251366
2,0.045421,0.080727,0.256421,0.232192,0.208285,0.451845,0.267327,0.665708,0.472095,0.261346,0.068392,0.390129,0.581559,0.243600,0.047554,0.159091,0.108818,0.111340,0.195652,0.151639
3,0.002374,0.039949,0.093114,0.073551,0.234714,0.622262,0.317132,0.598007,0.291400,0.207355,0.002850,0.103362,0.380826,0.372250,0.393650,0.034091,0.028143,0.020619,0.021739,0.114754
4,0.002726,0.041455,0.039036,0.035085,0.287655,0.555356,0.291629,0.567084,0.339433,0.233177,0.004159,0.146495,0.445915,0.441600,0.195258,0.000000,0.037523,0.000000,0.000000,0.057377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82386,0.008958,0.041286,0.068783,0.066100,0.235405,0.437144,0.222872,0.654339,0.510725,0.303991,0.017252,0.218026,0.662639,0.344300,0.042876,0.253788,0.048780,0.096220,0.094203,0.059199
82387,0.000482,0.045529,0.012304,0.011187,0.241094,0.513351,0.332283,0.519417,0.395242,0.310642,0.000000,0.074535,0.356588,0.530300,0.231367,0.079545,0.003752,0.000000,0.000000,0.012295
82388,0.000099,0.031933,0.016640,0.016358,0.205800,0.555055,0.308431,0.606328,0.357731,0.284820,0.008934,0.120887,0.479574,0.416700,0.217741,0.011364,0.018762,0.000000,0.000000,0.031421
82389,0.005252,0.045531,0.067978,0.061061,0.252030,0.442994,0.292454,0.633655,0.383501,0.278560,0.048906,0.282403,0.620037,0.296750,0.058727,0.164773,0.037523,0.016495,0.043478,0.056011
82390,0.001123,0.044803,0.037688,0.032481,0.204805,0.533453,0.311431,0.609616,0.378164,0.275039,0.007086,0.086123,0.435558,0.468300,0.223600,0.079545,0.022514,0.020619,0.021739,0.031421

In [30]:
#Agora vamos fazer a previsão
ceps_geral['Previsao_Zona'] =  floresta.predict(teste_geral)
ceps_geral

<ipython-input-30-d6063ec3bc6a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ceps_geral['Previsao_Zona'] =  floresta.predict(teste_geral)

,SETOR_ATIV,UF,MUNICIPIO,CEP,TRABALHADORES,S_RENDA_MEDIA,S_FLUXO_PEDESTRE,S_FLUXO_VEICULOS,S_POP_TOTAL,S_DOM_PART_PERM,...,S_DE_250_499_FUNC,S_DE_500_999_FUNC,S_MAIS1000_FUNC,S_SUPERMERCADO,S_TT_PADARIA,S_ATACADO,S_HIPERMERCADO,S_MINIMERCADO,cep_correto,Previsao_Zona
0,NaN,NaN,NaN,0.0,18776.596364,1852.325903,3.158788,4.933333,61660.275152,22297.529697,...,4.026667,2.001212,1.670303,8.768485,57.606061,23.126061,2.865455,85.970909,0,0
1,NaN,AC,Rio Branco,69900001.0,13125.000000,3502.669922,4.000000,6.000000,53376.000000,17146.000000,...,3.000000,4.000000,2.000000,3.000000,22.000000,3.000000,9.000000,184.000000,69900001,0
2,NaN,AC,Rio Branco,69900001.0,18364.000000,2477.159912,4.000000,6.000000,73460.000000,24698.000000,...,6.000000,2.000000,2.000000,14.000000,29.000000,27.000000,9.000000,111.000000,69900001,0
3,NaN,AC,Sena Madureira,0.0,960.000000,1225.869995,0.000000,0.000000,26675.500000,7823.500000,...,0.000000,0.500000,0.000000,3.000000,7.500000,5.000000,1.000000,84.000000,0,4
4,NaN,AC,Senador Guiomard,0.0,1102.000000,1272.079956,0.000000,1.000000,11183.000000,3732.000000,...,0.000000,1.000000,0.000000,0.000000,10.000000,0.000000,0.000000,42.000000,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82386,SERVICOS,TO,PARAISO DO TOCANTINS,77600000.0,3622.000000,1266.873372,1.333333,3.333333,19705.000000,7031.000000,...,0.333333,0.666667,0.000000,22.333333,13.000000,23.333333,4.333333,43.333333,77600000,2
82387,SERVICOS,TO,PAU D:ARCO,77785000.0,195.000000,1397.069946,0.000000,0.000000,3525.000000,1190.000000,...,0.000000,0.000000,0.000000,7.000000,1.000000,0.000000,0.000000,9.000000,77785000,0
82388,SERVICOS,TO,PEIXE,77460000.0,40.000000,979.869995,0.000000,2.000000,4767.000000,1740.000000,...,0.000000,0.000000,0.000000,1.000000,5.000000,0.000000,0.000000,23.000000,77460000,4
82389,SERVICOS,TO,PORTO NACIONAL,77500000.0,2123.500000,1397.145020,2.000000,5.000000,19474.500000,6495.000000,...,1.000000,0.000000,0.000000,14.500000,10.000000,4.000000,2.000000,41.000000,77500000,0
82390,SERVICOS,TO,XAMBIOA,77880000.0,454.000000,1374.800049,0.000000,1.000000,10797.000000,3455.000000,...,0.000000,0.000000,0.000000,7.000000,6.000000,5.000000,1.000000,23.000000,77880000,4

In [31]:
#Contanto quantas zonas 0
ceps_geral['Previsao_Zona'].value_counts().sort_values()

1      398
4    14065
0    20180
2    20376
3    23373
Name: Previsao_Zona, dtype: int64

In [32]:
mapa

{'Zona Sul': 0, 'Centro': 1, 'Zona Leste': 2, 'Zona Oeste': 3, 'Zona Norte': 4}

In [33]:
ceps_sp_zonas['Zona'].value_counts()

Zona Leste    1106
Zona Sul       980
Zona Norte     654
Zona Oeste     596
Centro         262
Name: Zona, dtype: int64

In [49]:
agrupamento_final = pd.DataFrame(ceps_geral[ceps_geral['Previsao_Zona'] == 0].groupby(['UF', 'MUNICIPIO'])['Previsao_Zona'].count()).reset_index()
agrupamento_final.sort_values('Previsao_Zona', ascending=False, inplace = True)
agrupamento_final[agrupamento_final['UF'] == 'CE']

     UF          MUNICIPIO  Previsao_Zona
304  CE          FORTALEZA            991
329  CE  JUAZEIRO DO NORTE            151
378  CE             SOBRAL            128
295  CE              CRATO            123
363  CE            QUIXADA             55
..   ..                ...            ...
309  CE          GRANJEIRO              1
311  CE       GUARAMIRANGA              1
317  CE      INDEPENDENCIA              1
319  CE                IPU              1
322  CE           ITAPIUNA              1

[121 rows x 3 columns]

In [50]:
agrupamento_final_pct = pd.DataFrame(ceps_geral[ceps_geral['Previsao_Zona'] == 0].groupby(['UF', 'MUNICIPIO'])['Previsao_Zona'].count()).reset_index()
agrupamento_final_pct.sort_values('Previsao_Zona', ascending=False, inplace = True)
agrupamento_final_pct['Contagem total'] = agrupamento_final_pct['MUNICIPIO'].apply(lambda x: ceps_geral.loc[(ceps_geral['MUNICIPIO'] == x), ['Previsao_Zona']].count())

In [59]:
agrupamento_final_pct['porcentagem'] = agrupamento_final_pct['Previsao_Zona']/agrupamento_final_pct['Contagem total']
agrupamento_final_pct.sort_values(['Previsao_Zona', 'porcentagem'], ascending=False, inplace = True)
agrupamento_final_pct['Previsa_Centro_Contragem'] = agrupamento_final_pct['MUNICIPIO'].apply(lambda x: ceps_geral.loc[(ceps_geral['MUNICIPIO'] == x) 
                                                                                                                    & (ceps_geral['Previsao_Zona'] == 1), ['Previsao_Zona']].count())
agrupamento_final_pct.head(20)

,UF,MUNICIPIO,Previsao_Zona,Contagem total,porcentagem,Previsa_Centro_Contragem
304,CE,FORTALEZA,991,2099,0.472130,36
562,MG,BELO HORIZONTE,696,1727,0.403011,50
1004,PR,CURITIBA,583,1524,0.382546,24
114,AM,MANAUS,511,803,0.636364,0
984,PI,TERESINA,454,866,0.524249,0
245,BA,SALVADOR,424,1274,0.332810,0
1235,RS,PORTO ALEGRE,420,961,0.437045,2
390,DF,BRASILIA,413,1629,0.253530,19
1100,RJ,RIO DE JANEIRO,382,2165,0.176443,196
36,AL,MACEIO,305,998,0.305611,0
433,GO,GOIANIA,263,664,0.396084,1
120,AM,Manaus,255,435,0.586207,0
1378,SP,CAMPINAS,240,678,0.353982,0
907,PE,RECIFE,235,693,0.339105,18
531,MA,SAO LUIS,228,472,0.483051,0
1151,RO,PORTO VELHO,219,459,0.477124,0
697,MG,UBERLANDIA,190,615,0.308943,0
1125,RN,NATAL,187,635,0.294488,1
810,PB,CAMPINA GRANDE,165,235,0.702128,0
710,MS,CAMPO GRANDE,159,582,0.273196,0

In [54]:
agrupamento_final_pct.shape

(1559, 5)